import stages as sta
import time
mystage=sta.Stage3()
time.sleep(5)
print(mystage.get_pos_mm())
mystage.set_pos_mm(0,0,0)
time.sleep(5)
print(mystage.get_pos_mm())
mystage.set_pos_mm(10,10,20)
time.sleep(5)
print(mystage.get_pos_mm())
mystage.set_pos_mm(20,20,40)
time.sleep(5)
print(mystage.get_pos_mm())
mystage.set_pos_mm(20,30,60)
time.sleep(5)
print(mystage.get_pos_mm())
mystage.set_pos_mm(20,40,80)
time.sleep(5)
print(mystage.get_pos_mm())
