import stages as sta
import time
mystage=sta.Stage3()
time.sleep(5)
print(mystage.get_pos_mm())
mystage.set_pos_mm(0,0,0)
time.sleep(5)
print(mystage.get_pos_mm())
mystage.set_pos_mm(0,10,0)
time.sleep(5)
print(mystage.get_pos_mm())
mystage.set_pos_mm(20,10,0)
time.sleep(5)
print(mystage.get_pos_mm())
mystage.set_pos_mm(20,30,0)
time.sleep(5)
print(mystage.get_pos_mm())
mystage.set_pos_mm(0,30,0)
time.sleep(5)
print(mystage.get_pos_mm())
mystage.set_pos_mm(10,20,0)
time.sleep(5)
print(mystage.get_pos_mm())
